version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: my-new-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: movie_ticket_booking
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: my-redis-container
    ports:
      - "6379:6379"

volumes:
  mysql-data:
