spring:
  application:
    name: movie-ticket-booking-system

  liquibase:
    enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/movie_ticket_booking
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true

  secret:
    key: "404D635166546A576E5A7234753778214125442A472D4B6150645267556B5870"

  cache:
    type: redis
    host: localhost
    port: 6379
    redis:
      time-to-live: 60000

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    virtual-host: /
    queue:
      status:
        name: statusQueue
      email:
        name: emailQueue

  mail:
    host: smtp.gmail.com
    port: 587
    username: ---
    password: ---
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
